name = "zkproof"
version = "0.1.0"
keywords = ["math", "cryptography", "zk proofs", "succinct proofs"]
defaultTargets = ["ZKProof"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ZKProof"
